h1: h1/main.go
	CGO_ENABLED=1 go run ./h1

h2: h2/main.go
	CGO_ENABLED=1 go run ./h2

h3: h3/main.go
	CGO_ENABLED=1 go run ./h3

h4: h4/main.go
	CGO_ENABLED=1 go run ./h4

h5: h5/main.go
	CGO_ENABLED=1 go run ./h5

h6: h6/main.go
	CGO_ENABLED=1 go run ./h6

h7: h7/main.go
	CGO_ENABLED=1 go run ./h7

h8: h8/main.go
	go run ./h8

forkfun: forkfun/main.go
	CGO_ENABLED=1 go run ./forkfun
