h1: h1.c
	gcc -o h1 h1.c -Wall && ./h1 && rm h1

h2: h2.c
	gcc -o h2 h2.c -Wall && ./h2 && rm h2

h3: h3.c
	gcc -o h3 h3.c -Wall && ./h3 && rm h3

h4: h4.c
	gcc -o h4 h4.c -Wall && ./h4 && rm h4

h5: h5.c
	gcc -o h5 h5.c -Wall && ./h5 && rm h5

h6: h6.c
	gcc -o h6 h6.c -Wall && ./h6 && rm h6
