h1: h1.rs
	cargo run --quiet --bin h1

h2: h2.rs
	cargo run --quiet --bin h2

h3: h3.rs
	cargo run --quiet --bin h3

h4: h4.rs
	cargo run --quiet --bin h4

h5: h5.rs
	cargo run --quiet --bin h5

h6: h6.rs
	cargo run --quiet --bin h6

h7: h7.rs
	cargo run --quiet --bin h7

h8: h8.rs
	cargo run --quiet --bin h8

h9: h9.rs
	cargo run --quiet --bin h9
